/** Structured log event names for video generation observability. */
export const VIDEO_GENERATION_EVENTS = {
  REQUESTED: 'VIDEO_GENERATION_REQUESTED',
  PROVIDER_SELECTED: 'VIDEO_PROVIDER_SELECTED',
  PROVIDER_STARTED: 'VIDEO_PROVIDER_STARTED',
  PROVIDER_FALLBACK: 'VIDEO_PROVIDER_FALLBACK',
  COMPLETED: 'VIDEO_GENERATION_COMPLETED',
  FAILED: 'VIDEO_GENERATION_FAILED',
} as const;

export type VideoGenerationEventName =
  (typeof VIDEO_GENERATION_EVENTS)[keyof typeof VIDEO_GENERATION_EVENTS];
