import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { randomUUID } from 'crypto';
import axios, { AxiosInstance } from 'axios';
import { FreemopayConfig } from '../../config/configuration';
import { normalizeProviderMessage } from '../normalize-provider-message';

export interface FreemopayPaymentRequest {
  payer: string;
  amount: number;
  externalId: string;
  description: string;
  callback: string;
}

export interface FreemopayWithdrawalRequest {
  payee: string;
  amount: number;
  externalId: string;
  description: string;
  callback: string;
}

export interface FreemopayPaymentResponse {
  success: boolean;
  transactionId?: string;
  reference?: string;
  paymentUrl?: string;
  message?: string;
  errorCode?: string;
  status?: string;
}

export interface FreemopayWithdrawalResponse {
  success: boolean;
  transactionId?: string;
  reference?: string;
  message?: string;
  errorCode?: string;
  status?: string;
}

export interface FreemopayTransactionStatus {
  transactionId: string;
  status: 'PENDING' | 'SUCCESS' | 'FAILED' | 'CANCELLED' | string;
  amount?: number;
  reference?: string;
  merchantRef?: string;
  reason?: string;
  message?: string;
}

@Injectable()
export class FreemopayService {
  private readonly logger = new Logger(FreemopayService.name);
  private readonly httpClient: AxiosInstance;
  private readonly config: FreemopayConfig;
  private readonly mockEnabled: boolean;
  private readonly mockThreshold = 2000;
  private readonly mockOutcomes = new Map<string, { outcome: 'SUCCESS' | 'FAILED'; amount: number }>();

  constructor(private readonly configService: ConfigService) {
    const freemopayConfig = this.configService.get<FreemopayConfig>('freemopay');

    this.config = {
      baseUrl: freemopayConfig?.baseUrl?.replace(/\/$/, '') || 'https://api-v2.freemopay.com',
      appKey: freemopayConfig?.appKey || '',
      secretKey: freemopayConfig?.secretKey || '',
      callbackUrl: freemopayConfig?.callbackUrl || '',
      amountMockEnabled: freemopayConfig?.amountMockEnabled ?? false,
    };

    this.mockEnabled = this.config.amountMockEnabled;

    this.logger.log('Freemopay configuration loaded');
    this.logger.log(`- Base URL: ${this.config.baseUrl}`);
    this.logger.log(`- App key: ${this.config.appKey ? 'SET' : 'EMPTY'}`);
    if (this.mockEnabled) {
      this.logger.warn(
        `⚠️  FreemoPay DEV MOCK ENABLED: amounts < ${this.mockThreshold} XAF will simulate SUCCESS, >= ${this.mockThreshold} XAF will simulate FAILED. NO LIVE API CALLS.`
      );
    }

    const auth =
      this.config.appKey && this.config.secretKey
        ? Buffer.from(
            `${this.config.appKey}:${this.config.secretKey}`,
            'utf-8'
          ).toString('base64')
        : '';

    this.httpClient = axios.create({
      baseURL: this.config.baseUrl,
      timeout: 30000,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        ...(auth ? { Authorization: `Basic ${auth}` } : {}),
      },
    });

    this.httpClient.interceptors.response.use(
      (response) => {
        this.logger.debug(
          `Freemopay API Response: ${response.status}`,
          response.data
        );
        return response;
      },
      (error) => {
        this.logger.error(
          'Freemopay API Error:',
          error.response?.data || error.message
        );
        return Promise.reject(error);
      }
    );
  }

  /**
   * Check if a transaction ID was generated by the mock (starts with mock-).
   */
  private isMockedTransaction(reference: string): boolean {
    return reference?.startsWith('mock-') ?? false;
  }

  /**
   * Generate a synthetic mock transaction ID.
   */
  private generateMockReference(): string {
    return `mock-${randomUUID()}`;
  }

  /**
   * Determine mock outcome based on amount threshold.
   * < 2000 XAF = SUCCESS, >= 2000 XAF = FAILED.
   */
  private getMockOutcome(amount: number): 'SUCCESS' | 'FAILED' {
    return amount < this.mockThreshold ? 'SUCCESS' : 'FAILED';
  }

  /**
   * Simulate a mock payment initiation.
   */
  private mockInitiatePayment(
    paymentRequest: FreemopayPaymentRequest,
    reference?: string
  ): FreemopayPaymentResponse {
    const externalId = reference || paymentRequest.externalId;
    const mockRef = this.generateMockReference();
    const outcome = this.getMockOutcome(paymentRequest.amount);

    // Store the outcome for later status checks
    this.mockOutcomes.set(mockRef, { outcome, amount: paymentRequest.amount });

    this.logger.log(
      `🔨 MOCK FreemoPay payment: amount=${paymentRequest.amount} XAF, payer=${paymentRequest.payer}, reference=${externalId}, mock_ref=${mockRef}, outcome=${outcome}`
    );

    return {
      success: true,
      transactionId: mockRef,
      reference: mockRef,
      status: 'PENDING',
      message: normalizeProviderMessage(null, 'Mock payment initiated'),
    };
  }

  /**
   * Simulate a mock withdrawal initiation.
   */
  private mockWithdraw(
    withdrawalRequest: FreemopayWithdrawalRequest,
    reference?: string
  ): FreemopayWithdrawalResponse {
    const externalId = reference || withdrawalRequest.externalId;
    const mockRef = this.generateMockReference();
    const outcome = this.getMockOutcome(withdrawalRequest.amount);

    // Store the outcome for later status checks
    this.mockOutcomes.set(mockRef, { outcome, amount: withdrawalRequest.amount });

    this.logger.log(
      `🔨 MOCK FreemoPay withdrawal: amount=${withdrawalRequest.amount} XAF, payee=${withdrawalRequest.payee}, reference=${externalId}, mock_ref=${mockRef}, outcome=${outcome}`
    );

    return {
      success: true,
      transactionId: mockRef,
      reference: mockRef,
      status: 'CREATED',
      message: normalizeProviderMessage(null, 'Mock withdrawal initiated'),
    };
  }

  /**
   * Initialize a payment transaction (POST /api/v2/payment)
   */
  async initiatePayment(
    paymentRequest: FreemopayPaymentRequest,
    reference?: string
  ): Promise<FreemopayPaymentResponse> {
    if (this.mockEnabled) {
      return this.mockInitiatePayment(paymentRequest, reference);
    }

    try {
      const externalId = reference || paymentRequest.externalId;
      this.logger.log(
        `Initiating Freemopay payment for payer: ${paymentRequest.payer}, externalId: ${externalId}, callback: ${paymentRequest.callback}`
      );

      const payload = {
        payer: paymentRequest.payer,
        amount: paymentRequest.amount,
        externalId,
        description: paymentRequest.description || 'Payment',
        callback: paymentRequest.callback,
      };

      const response = await this.httpClient.post('/api/v2/payment', payload);

      const data = response.data;
      this.logger.log(`Freemopay API Response: ${JSON.stringify(data)}`);
      if (response.status === 200 && data?.reference) {
        return {
          success: true,
          transactionId: data.reference,
          reference: data.reference,
          status: data.status,
          message: normalizeProviderMessage(data.message, 'Payment initiated'),
        };
      }

      return {
        success: false,
        message: normalizeProviderMessage(
          data?.message,
          'Payment initiation failed'
        ),
        errorCode: data?.statusCode?.toString() || 'UNKNOWN_ERROR',
        status: data?.status,
      };
    } catch (error: any) {
      this.logger.error('Failed to initiate Freemopay payment:', error);
      return {
        success: false,
        message: normalizeProviderMessage(
          error.response?.data?.message,
          'Failed to initiate payment'
        ),
        errorCode:
          error.response?.data?.statusCode?.toString() ||
          error.response?.status?.toString() ||
          'INITIATION_FAILED',
        status: 'FAILED',
      };
    }
  }

  /**
   * Initialize a withdrawal (POST /api/v2/payment/direct-withdraw).
   * Request: receiver (phone), amount, externalId, callback. Basic Auth.
   */
  async withdraw(
    withdrawalRequest: FreemopayWithdrawalRequest,
    reference?: string
  ): Promise<FreemopayWithdrawalResponse> {
    if (this.mockEnabled) {
      return this.mockWithdraw(withdrawalRequest, reference);
    }

    try {
      const externalId = reference || withdrawalRequest.externalId;
      this.logger.log(
        `Initiating Freemopay withdrawal for receiver: ${withdrawalRequest.payee}, externalId: ${externalId}, callback: ${withdrawalRequest.callback}`
      );

      const payload = {
        receiver: withdrawalRequest.payee,
        amount: withdrawalRequest.amount,
        externalId,
        callback: withdrawalRequest.callback,
      };

      const response = await this.httpClient.post(
        '/api/v2/payment/direct-withdraw',
        payload
      );

      const data = response.data;
      this.logger.log(`Freemopay withdrawal API Response: ${JSON.stringify(data)}`);

      const success =
        response.status === 200 &&
        (data?.reference || data?.status === 'CREATED');
      if (success) {
        return {
          success: true,
          transactionId: data.reference ?? externalId,
          reference: data.reference ?? externalId,
          status: data.status,
          message: normalizeProviderMessage(
            data.message,
            'Withdrawal initiated'
          ),
        };
      }

      return {
        success: false,
        message: normalizeProviderMessage(
          data?.message,
          'Withdrawal initiation failed'
        ),
        errorCode: data?.statusCode?.toString() || 'UNKNOWN_ERROR',
        status: data?.status,
      };
    } catch (error: any) {
      this.logger.error('Failed to initiate Freemopay withdrawal:', error);
      return {
        success: false,
        message: normalizeProviderMessage(
          error.response?.data?.message,
          'Failed to initiate withdrawal'
        ),
        errorCode:
          error.response?.data?.statusCode?.toString() ||
          error.response?.status?.toString() ||
          'WITHDRAWAL_FAILED',
        status: 'FAILED',
      };
    }
  }

  /**
   * Check transaction status (GET /api/v2/payment/:reference)
   */
  async checkTransactionStatus(
    reference: string
  ): Promise<FreemopayTransactionStatus> {
    if (this.isMockedTransaction(reference)) {
      return this.getMockTransactionStatus(reference);
    }

    try {
      this.logger.log(`Checking Freemopay transaction status: ${reference}`);

      const response = await this.httpClient.get(
        `/api/v2/payment/${encodeURIComponent(reference)}`
      );

      const data = response.data;
      const merchantRef = data.merchantRef ?? data.merchandRef;

      return {
        transactionId: data.reference || reference,
        status: data.status || 'PENDING',
        amount: data.amount,
        reference: data.reference,
        merchantRef,
        reason:
          typeof data.reason === 'string'
            ? data.reason
            : normalizeProviderMessage(data.reason, ''),
        message: normalizeProviderMessage(
          data.reason || data.message,
          'Status check completed'
        ),
      };
    } catch (error: any) {
      this.logger.error(
        'Failed to check Freemopay transaction status:',
        error
      );
      throw error;
    }
  }

  /**
   * Get mocked transaction status.
   * Returns the predetermined outcome based on the amount threshold.
   */
  private getMockTransactionStatus(reference: string): FreemopayTransactionStatus {
    const stored = this.mockOutcomes.get(reference);
    
    if (!stored) {
      this.logger.warn(`🔨 MOCK FreemoPay status check: ${reference} (not found in mock outcomes, returning PENDING)`);
      return {
        transactionId: reference,
        status: 'PENDING',
        amount: 0,
        reference,
        merchantRef: '',
        message: 'Mock transaction not found',
      };
    }

    const status = stored.outcome;
    this.logger.log(`🔨 MOCK FreemoPay status check: ${reference}, amount=${stored.amount} XAF, outcome=${status}`);
    
    return {
      transactionId: reference,
      status,
      amount: stored.amount,
      reference,
      merchantRef: '',
      reason: status === 'FAILED' ? 'Mock failure (amount >= threshold)' : undefined,
      message: status === 'SUCCESS' 
        ? 'Mock transaction succeeded' 
        : 'Mock transaction failed (amount >= threshold)',
    };
  }

  /**
   * Verify payment callback payload (shape validation only; no signature in doc)
   */
  verifyCallback(
    _payload: unknown,
    _signature?: string,
    _timestamp?: string
  ): boolean {
    if (!_payload || typeof _payload !== 'object') return false;
    const p = _payload as Record<string, unknown>;
    return (
      typeof p.reference === 'string' && typeof p.status === 'string'
    );
  }

  /**
   * Get supported payment methods
   */
  async getSupportedPaymentMethods(): Promise<string[]> {
    return ['mobile_money'];
  }

  /**
   * Cancel a pending transaction (Freemopay API does not document cancel; no-op)
   */
  async cancelTransaction(_reference: string): Promise<boolean> {
    this.logger.warn(
      'Freemopay does not support transaction cancellation via API'
    );
    return false;
  }

  /**
   * Get callback URL from config
   */
  getCallbackUrl(): string {
    return this.config.callbackUrl;
  }

  /**
   * Test connection: checks that credentials and callback URL are configured.
   */
  async testConnection(): Promise<boolean> {
    return !!(
      this.config.appKey &&
      this.config.secretKey &&
      this.config.callbackUrl
    );
  }

  /**
   * Generate a mock callback payload for a given mock transaction.
   * Useful for testing the callback flow with mocked transactions.
   */
  generateMockCallback(
    mockReference: string,
    externalId?: string,
    outcome?: 'SUCCESS' | 'FAILED'
  ): {
    reference: string;
    status: 'SUCCESS' | 'FAILED';
    merchantRef?: string;
    externalId?: string;
    message: string;
    reason?: string;
  } {
    const stored = this.mockOutcomes.get(mockReference);
    const finalOutcome = outcome ?? stored?.outcome ?? 'SUCCESS';

    return {
      reference: mockReference,
      status: finalOutcome,
      merchantRef: externalId,
      externalId,
      message:
        finalOutcome === 'SUCCESS'
          ? 'Mock payment succeeded'
          : 'Mock payment failed (amount >= threshold)',
      reason:
        finalOutcome === 'FAILED'
          ? 'Mock failure (amount >= threshold)'
          : undefined,
    };
  }
}
