-- Migration: seed_countries_tg_bj_ci_cg
-- Description: Onboard TG, BJ, CI, CG as active markets.
--              State/country names from country-state-city@3.2.1.
--              No supported_payment_systems rows — payment rails not integrated yet.

-- 1. supported_country_states
INSERT INTO public.supported_country_states (
    country_code, country_name, state_name, currency_code,
    service_status, delivery_enabled, launch_date
)
SELECT v.country_code, v.country_name, v.state_name, v.currency_code,
       v.service_status, v.delivery_enabled, v.launch_date
FROM (VALUES
    ('TG', 'Togo', 'Centrale Region', 'XOF', 'active', true, CURRENT_DATE),
    ('TG', 'Togo', 'Kara Region', 'XOF', 'active', true, CURRENT_DATE),
    ('TG', 'Togo', 'Maritime', 'XOF', 'active', true, CURRENT_DATE),
    ('TG', 'Togo', 'Plateaux Region', 'XOF', 'active', true, CURRENT_DATE),
    ('TG', 'Togo', 'Savanes Region', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Alibori Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Atakora Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Atlantique Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Borgou Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Collines Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Donga Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Kouffo Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Littoral Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Mono Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Ouémé Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Plateau Department', 'XOF', 'active', true, CURRENT_DATE),
    ('BJ', 'Benin', 'Zou Department', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Abidjan', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Agnéby', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Bafing Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Bas-Sassandra District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Bas-Sassandra Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Comoé District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Denguélé District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Denguélé Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Dix-Huit Montagnes', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Fromager', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Gôh-Djiboua District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Haut-Sassandra', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Lacs District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Lacs Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Lagunes District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Lagunes region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Marahoué Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Montagnes District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Moyen-Cavally', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Moyen-Comoé', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'N''zi-Comoé', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Sassandra-Marahoué District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Savanes Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Sud-Bandama', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Sud-Comoé', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Vallée du Bandama District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Vallée du Bandama Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Woroba District', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Worodougou', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Yamoussoukro', 'XOF', 'active', true, CURRENT_DATE),
    ('CI', 'Cote D''Ivoire (Ivory Coast)', 'Zanzan Region', 'XOF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Bouenza Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Brazzaville', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Cuvette Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Cuvette-Ouest Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Kouilou Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Likouala Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Lékoumou Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Niari Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Plateaux Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Pointe-Noire', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Pool Department', 'XAF', 'active', true, CURRENT_DATE),
    ('CG', 'Congo', 'Sangha Department', 'XAF', 'active', true, CURRENT_DATE)
) AS v(country_code, country_name, state_name, currency_code, service_status, delivery_enabled, launch_date)
WHERE NOT EXISTS (
    SELECT 1 FROM public.supported_country_states s
    WHERE s.country_code = v.country_code AND s.state_name = v.state_name
);

-- 2. country_delivery_configs
INSERT INTO public.country_delivery_configs (country_code, config_key, config_value, data_type) VALUES
    ('TG', 'normal_delivery_base_fee', '1000', 'number'),
    ('TG', 'fast_delivery_base_fee', '1500', 'number'),
    ('TG', 'per_km_delivery_fee', '100', 'number'),
    ('TG', 'max_per_km_delivery_fee', '1500', 'number'),
    ('TG', 'fast_delivery_sla', '4', 'number'),
    ('TG', 'fast_delivery_service_hours', '{"friday": {"end": "20:00", "start": "08:00", "enabled": true}, "monday": {"end": "20:00", "start": "08:00", "enabled": true}, "sunday": {"end": "16:00", "start": "10:00", "enabled": false}, "tuesday": {"end": "20:00", "start": "08:00", "enabled": true}, "saturday": {"end": "18:00", "start": "09:00", "enabled": true}, "thursday": {"end": "20:00", "start": "08:00", "enabled": true}, "wednesday": {"end": "20:00", "start": "08:00", "enabled": true}}', 'json'),
    ('TG', 'fast_delivery_enabled', 'true', 'boolean'),
    ('TG', 'currency', 'XOF', 'string'),
    ('TG', 'timezone', 'Africa/Lome', 'string'),
    ('TG', 'failed_delivery_fees', '200', 'number'),
    ('TG', 'delivery_availability_radius_km', '20', 'number'),
    ('BJ', 'normal_delivery_base_fee', '1000', 'number'),
    ('BJ', 'fast_delivery_base_fee', '1500', 'number'),
    ('BJ', 'per_km_delivery_fee', '100', 'number'),
    ('BJ', 'max_per_km_delivery_fee', '1500', 'number'),
    ('BJ', 'fast_delivery_sla', '4', 'number'),
    ('BJ', 'fast_delivery_service_hours', '{"friday": {"end": "20:00", "start": "08:00", "enabled": true}, "monday": {"end": "20:00", "start": "08:00", "enabled": true}, "sunday": {"end": "16:00", "start": "10:00", "enabled": false}, "tuesday": {"end": "20:00", "start": "08:00", "enabled": true}, "saturday": {"end": "18:00", "start": "09:00", "enabled": true}, "thursday": {"end": "20:00", "start": "08:00", "enabled": true}, "wednesday": {"end": "20:00", "start": "08:00", "enabled": true}}', 'json'),
    ('BJ', 'fast_delivery_enabled', 'true', 'boolean'),
    ('BJ', 'currency', 'XOF', 'string'),
    ('BJ', 'timezone', 'Africa/Porto-Novo', 'string'),
    ('BJ', 'failed_delivery_fees', '200', 'number'),
    ('BJ', 'delivery_availability_radius_km', '20', 'number'),
    ('CI', 'normal_delivery_base_fee', '1000', 'number'),
    ('CI', 'fast_delivery_base_fee', '1500', 'number'),
    ('CI', 'per_km_delivery_fee', '100', 'number'),
    ('CI', 'max_per_km_delivery_fee', '1500', 'number'),
    ('CI', 'fast_delivery_sla', '4', 'number'),
    ('CI', 'fast_delivery_service_hours', '{"friday": {"end": "20:00", "start": "08:00", "enabled": true}, "monday": {"end": "20:00", "start": "08:00", "enabled": true}, "sunday": {"end": "16:00", "start": "10:00", "enabled": false}, "tuesday": {"end": "20:00", "start": "08:00", "enabled": true}, "saturday": {"end": "18:00", "start": "09:00", "enabled": true}, "thursday": {"end": "20:00", "start": "08:00", "enabled": true}, "wednesday": {"end": "20:00", "start": "08:00", "enabled": true}}', 'json'),
    ('CI', 'fast_delivery_enabled', 'true', 'boolean'),
    ('CI', 'currency', 'XOF', 'string'),
    ('CI', 'timezone', 'Africa/Abidjan', 'string'),
    ('CI', 'failed_delivery_fees', '200', 'number'),
    ('CI', 'delivery_availability_radius_km', '20', 'number'),
    ('CG', 'normal_delivery_base_fee', '1000', 'number'),
    ('CG', 'fast_delivery_base_fee', '1500', 'number'),
    ('CG', 'per_km_delivery_fee', '100', 'number'),
    ('CG', 'max_per_km_delivery_fee', '1500', 'number'),
    ('CG', 'fast_delivery_sla', '4', 'number'),
    ('CG', 'fast_delivery_service_hours', '{"friday": {"end": "20:00", "start": "08:00", "enabled": true}, "monday": {"end": "20:00", "start": "08:00", "enabled": true}, "sunday": {"end": "16:00", "start": "10:00", "enabled": false}, "tuesday": {"end": "20:00", "start": "08:00", "enabled": true}, "saturday": {"end": "18:00", "start": "09:00", "enabled": true}, "thursday": {"end": "20:00", "start": "08:00", "enabled": true}, "wednesday": {"end": "20:00", "start": "08:00", "enabled": true}}', 'json'),
    ('CG', 'fast_delivery_enabled', 'true', 'boolean'),
    ('CG', 'currency', 'XAF', 'string'),
    ('CG', 'timezone', 'Africa/Brazzaville', 'string'),
    ('CG', 'failed_delivery_fees', '200', 'number'),
    ('CG', 'delivery_availability_radius_km', '20', 'number')
ON CONFLICT (country_code, config_key) DO UPDATE
SET config_value = EXCLUDED.config_value,
    data_type = EXCLUDED.data_type,
    updated_at = NOW();

-- 3. delivery_time_slots (per-state + __DEFAULT__)
INSERT INTO public.delivery_time_slots (country_code, state, slot_name, slot_type, start_time, end_time, max_orders_per_slot, display_order) VALUES
('TG', 'Centrale Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('TG', 'Centrale Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('TG', 'Centrale Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('TG', 'Kara Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('TG', 'Kara Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('TG', 'Kara Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('TG', 'Maritime', 'Morning', 'standard', '08:00', '12:00', 15, 1),
('TG', 'Maritime', 'Afternoon', 'standard', '12:00', '16:00', 15, 2),
('TG', 'Maritime', 'Evening', 'standard', '16:00', '20:00', 15, 3),
('TG', 'Maritime', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('TG', 'Maritime', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('TG', 'Maritime', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('TG', 'Plateaux Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('TG', 'Plateaux Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('TG', 'Plateaux Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('TG', 'Savanes Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('TG', 'Savanes Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('TG', 'Savanes Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('TG', '__DEFAULT__', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('TG', '__DEFAULT__', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('TG', '__DEFAULT__', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('TG', '__DEFAULT__', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('TG', '__DEFAULT__', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('TG', '__DEFAULT__', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('BJ', 'Alibori Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Alibori Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Alibori Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Atakora Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Atakora Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Atakora Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Atlantique Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Atlantique Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Atlantique Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Borgou Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Borgou Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Borgou Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Collines Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Collines Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Collines Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Donga Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Donga Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Donga Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Kouffo Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Kouffo Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Kouffo Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Littoral Department', 'Morning', 'standard', '08:00', '12:00', 15, 1),
('BJ', 'Littoral Department', 'Afternoon', 'standard', '12:00', '16:00', 15, 2),
('BJ', 'Littoral Department', 'Evening', 'standard', '16:00', '20:00', 15, 3),
('BJ', 'Littoral Department', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('BJ', 'Littoral Department', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('BJ', 'Littoral Department', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('BJ', 'Mono Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Mono Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Mono Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Ouémé Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Ouémé Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Ouémé Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Plateau Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Plateau Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Plateau Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', 'Zou Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', 'Zou Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', 'Zou Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', '__DEFAULT__', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('BJ', '__DEFAULT__', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('BJ', '__DEFAULT__', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('BJ', '__DEFAULT__', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('BJ', '__DEFAULT__', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('BJ', '__DEFAULT__', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('CI', 'Abidjan', 'Morning', 'standard', '08:00', '12:00', 15, 1),
('CI', 'Abidjan', 'Afternoon', 'standard', '12:00', '16:00', 15, 2),
('CI', 'Abidjan', 'Evening', 'standard', '16:00', '20:00', 15, 3),
('CI', 'Abidjan', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('CI', 'Abidjan', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('CI', 'Abidjan', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('CI', 'Agnéby', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Agnéby', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Agnéby', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Bafing Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Bafing Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Bafing Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Bas-Sassandra District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Bas-Sassandra District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Bas-Sassandra District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Bas-Sassandra Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Bas-Sassandra Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Bas-Sassandra Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Comoé District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Comoé District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Comoé District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Denguélé District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Denguélé District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Denguélé District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Denguélé Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Denguélé Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Denguélé Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Dix-Huit Montagnes', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Dix-Huit Montagnes', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Dix-Huit Montagnes', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Fromager', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Fromager', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Fromager', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Gôh-Djiboua District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Gôh-Djiboua District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Gôh-Djiboua District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Haut-Sassandra', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Haut-Sassandra', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Haut-Sassandra', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Lacs District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Lacs District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Lacs District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Lacs Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Lacs Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Lacs Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Lagunes District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Lagunes District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Lagunes District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Lagunes region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Lagunes region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Lagunes region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Marahoué Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Marahoué Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Marahoué Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Montagnes District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Montagnes District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Montagnes District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Moyen-Cavally', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Moyen-Cavally', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Moyen-Cavally', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Moyen-Comoé', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Moyen-Comoé', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Moyen-Comoé', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'N''zi-Comoé', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'N''zi-Comoé', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'N''zi-Comoé', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Sassandra-Marahoué District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Sassandra-Marahoué District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Sassandra-Marahoué District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Savanes Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Savanes Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Savanes Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Sud-Bandama', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Sud-Bandama', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Sud-Bandama', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Sud-Comoé', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Sud-Comoé', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Sud-Comoé', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Vallée du Bandama District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Vallée du Bandama District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Vallée du Bandama District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Vallée du Bandama Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Vallée du Bandama Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Vallée du Bandama Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Woroba District', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Woroba District', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Woroba District', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Worodougou', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Worodougou', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Worodougou', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Yamoussoukro', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Yamoussoukro', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Yamoussoukro', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', 'Zanzan Region', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', 'Zanzan Region', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', 'Zanzan Region', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', '__DEFAULT__', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CI', '__DEFAULT__', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CI', '__DEFAULT__', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CI', '__DEFAULT__', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('CI', '__DEFAULT__', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('CI', '__DEFAULT__', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('CG', 'Bouenza Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Bouenza Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Bouenza Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Brazzaville', 'Morning', 'standard', '08:00', '12:00', 15, 1),
('CG', 'Brazzaville', 'Afternoon', 'standard', '12:00', '16:00', 15, 2),
('CG', 'Brazzaville', 'Evening', 'standard', '16:00', '20:00', 15, 3),
('CG', 'Brazzaville', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('CG', 'Brazzaville', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('CG', 'Brazzaville', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('CG', 'Cuvette Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Cuvette Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Cuvette Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Cuvette-Ouest Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Cuvette-Ouest Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Cuvette-Ouest Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Kouilou Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Kouilou Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Kouilou Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Likouala Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Likouala Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Likouala Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Lékoumou Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Lékoumou Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Lékoumou Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Niari Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Niari Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Niari Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Plateaux Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Plateaux Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Plateaux Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Pointe-Noire', 'Morning', 'standard', '08:00', '12:00', 15, 1),
('CG', 'Pointe-Noire', 'Afternoon', 'standard', '12:00', '16:00', 15, 2),
('CG', 'Pointe-Noire', 'Evening', 'standard', '16:00', '20:00', 15, 3),
('CG', 'Pointe-Noire', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('CG', 'Pointe-Noire', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('CG', 'Pointe-Noire', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6),
('CG', 'Pool Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Pool Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Pool Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', 'Sangha Department', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', 'Sangha Department', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', 'Sangha Department', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', '__DEFAULT__', 'Morning', 'standard', '08:00', '12:00', 10, 1),
('CG', '__DEFAULT__', 'Afternoon', 'standard', '12:00', '16:00', 10, 2),
('CG', '__DEFAULT__', 'Evening', 'standard', '16:00', '20:00', 10, 3),
('CG', '__DEFAULT__', 'Morning Fast', 'fast', '09:00', '12:00', 5, 4),
('CG', '__DEFAULT__', 'Afternoon Fast', 'fast', '13:00', '16:00', 5, 5),
('CG', '__DEFAULT__', 'Evening Fast', 'fast', '17:00', '20:00', 5, 6)
ON CONFLICT ON CONSTRAINT unique_slot_per_location DO NOTHING;

-- 4. country_onboarding_configs (no payment systems)
INSERT INTO public.country_onboarding_configs (
  country_code, signup_enabled, postal_code_required, verification_flow, default_currency
) VALUES
  ('TG', true, false, 'national_id', 'XOF'),
  ('BJ', true, false, 'national_id', 'XOF'),
  ('CI', true, false, 'national_id', 'XOF'),
  ('CG', true, false, 'national_id', 'XAF')
ON CONFLICT (country_code) DO UPDATE
SET signup_enabled = EXCLUDED.signup_enabled,
    postal_code_required = EXCLUDED.postal_code_required,
    verification_flow = EXCLUDED.verification_flow,
    default_currency = EXCLUDED.default_currency,
    updated_at = NOW();

-- 5. Clone Cameroon application_configurations for each new market
INSERT INTO public.application_configurations (
  config_key, config_name, description, data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  country_code, status, version, tags, validation_rules,
  min_value, max_value, allowed_values
)
SELECT
  config_key,
  replace(config_name, 'Cameroon', 'Togo'),
  replace(replace(description, 'XAF', 'XOF'), 'Cameroon', 'Togo'),
  data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  'TG',
  status, version, tags, validation_rules,
  min_value, max_value, allowed_values
FROM public.application_configurations
WHERE country_code = 'CM'
ON CONFLICT (config_key, country_code) DO NOTHING;

INSERT INTO public.application_configurations (
  config_key, config_name, description, data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  country_code, status, version, tags, validation_rules,
  min_value, max_value, allowed_values
)
SELECT
  config_key,
  replace(config_name, 'Cameroon', 'Benin'),
  replace(replace(description, 'XAF', 'XOF'), 'Cameroon', 'Benin'),
  data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  'BJ',
  status, version, tags, validation_rules,
  min_value, max_value, allowed_values
FROM public.application_configurations
WHERE country_code = 'CM'
ON CONFLICT (config_key, country_code) DO NOTHING;

INSERT INTO public.application_configurations (
  config_key, config_name, description, data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  country_code, status, version, tags, validation_rules,
  min_value, max_value, allowed_values
)
SELECT
  config_key,
  replace(config_name, 'Cameroon', 'Côte d''Ivoire'),
  replace(replace(description, 'XAF', 'XOF'), 'Cameroon', 'Côte d''Ivoire'),
  data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  'CI',
  status, version, tags, validation_rules,
  min_value, max_value, allowed_values
FROM public.application_configurations
WHERE country_code = 'CM'
ON CONFLICT (config_key, country_code) DO NOTHING;

INSERT INTO public.application_configurations (
  config_key, config_name, description, data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  country_code, status, version, tags, validation_rules,
  min_value, max_value, allowed_values
)
SELECT
  config_key,
  replace(config_name, 'Cameroon', 'Congo'),
  replace(description, 'Cameroon', 'Congo'),
  data_type,
  string_value, number_value, boolean_value, json_value, array_value, date_value,
  'CG',
  status, version, tags, validation_rules,
  min_value, max_value, allowed_values
FROM public.application_configurations
WHERE country_code = 'CM'
ON CONFLICT (config_key, country_code) DO NOTHING;

