-- Add delivery PIN and overwrite code columns to orders (PIN-based completion flow)
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS delivery_pin_hash TEXT,
  ADD COLUMN IF NOT EXISTS delivery_pin_attempts INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_overwrite_code_hash TEXT,
  ADD COLUMN IF NOT EXISTS delivery_overwrite_code_used_at TIMESTAMPTZ;

COMMENT ON COLUMN public.orders.delivery_pin_hash IS 'Hash of the 4-digit delivery PIN; set when order becomes paid';
COMMENT ON COLUMN public.orders.delivery_pin_attempts IS 'Number of failed PIN attempts for this order (max 3)';
COMMENT ON COLUMN public.orders.delivery_overwrite_code_hash IS 'Hash of overwrite code generated by business';
COMMENT ON COLUMN public.orders.delivery_overwrite_code_used_at IS 'When overwrite code was used to complete the order';
