"""
Pydantic models generated from Hasura metadata.

Models are generated by `generate_models.py` into individual files in this
package and re-exported here via the `__all__` list for convenient imports.

Usage:
    from rendasua_core_packages.models import User, Order, Account
"""

# Explicit imports of all model classes
# Note: Relative imports (from .module) require this file to be imported as part of a package
# Do not run this file directly - import it as: from rendasua_core_packages.models import ...
from .Account import Account
from .AccountTransaction import AccountTransaction
from .BalanceUpdate import BalanceUpdate
from .Address import Address
from .Agent import Agent
from .AgentAddress import AgentAddress
from .AgentLocation import AgentLocation
from .AirtelMoneyPayment import AirtelMoneyPayment
from .ApplicationConfiguration import ApplicationConfiguration
from .Brand import Brand
from .Business import Business
from .BusinessAddress import BusinessAddress
from .BusinessInventory import BusinessInventory
from .BusinessLocation import BusinessLocation
from .Client import Client
from .ClientAddress import ClientAddress
from .Coordinates import Coordinates
from .CommissionPayout import CommissionPayout
from .CountryDeliveryConfig import CountryDeliveryConfig
from .DeliveryConfig import DeliveryConfig
from .DeliveryTimeSlot import DeliveryTimeSlot
from .DeliveryTimeWindow import DeliveryTimeWindow
from .DocumentType import DocumentType
from .EntityType import EntityType
from .GoogleDistanceCache import GoogleDistanceCache
from .GoogleGeocodeCache import GoogleGeocodeCache
from .Item import Item
from .ItemCategory import ItemCategory
from .ItemImage import ItemImage
from .ItemSubCategory import ItemSubCategory
from .MobilePaymentTransaction import MobilePaymentTransaction
from .MtnMomoPaymentRequest import MtnMomoPaymentRequest
from .Order import Order
from .OrderCancellationReason import OrderCancellationReason
from .OrderHold import OrderHold
from .OrderItem import OrderItem
from .OrderStatuHistory import OrderStatuHistory
from .Partner import Partner
from .TransactionInfo import TransactionInfo
from .PaymentCallback import PaymentCallback
from .Rating import Rating
from .RatingAggregate import RatingAggregate
from .SupportedCountryState import SupportedCountryState
from .SupportedPaymentSystem import SupportedPaymentSystem
from .User import User
from .UserMessage import UserMessage
from .UserType import UserType
from .UserUpload import UserUpload
from .VehicleType import VehicleType

# Rebuild models with forward references
# This resolves forward references after all models are imported
# Models are rebuilt in dependency order to ensure all referenced models are available
Account.model_rebuild()
AccountTransaction.model_rebuild()
Address.model_rebuild()
Agent.model_rebuild()
AgentAddress.model_rebuild()
AgentLocation.model_rebuild()
AirtelMoneyPayment.model_rebuild()
Business.model_rebuild()
BusinessAddress.model_rebuild()
BusinessInventory.model_rebuild()
BusinessLocation.model_rebuild()
Client.model_rebuild()
ClientAddress.model_rebuild()
CommissionPayout.model_rebuild()
CountryDeliveryConfig.model_rebuild()
DeliveryTimeWindow.model_rebuild()
Item.model_rebuild()
ItemImage.model_rebuild()
ItemSubCategory.model_rebuild()
MobilePaymentTransaction.model_rebuild()
MtnMomoPaymentRequest.model_rebuild()
Order.model_rebuild()
OrderHold.model_rebuild()
OrderItem.model_rebuild()
OrderStatuHistory.model_rebuild()
Partner.model_rebuild()
PaymentCallback.model_rebuild()
Rating.model_rebuild()
TransactionInfo.model_rebuild()
User.model_rebuild()
UserUpload.model_rebuild()
VehicleType.model_rebuild()

# Explicit __all__ list
__all__: list[str] = [
    "Account",
    "AccountTransaction",
    "BalanceUpdate",
    "Address",
    "Agent",
    "AgentAddress",
    "AgentLocation",
    "AirtelMoneyPayment",
    "ApplicationConfiguration",
    "Brand",
    "Business",
    "BusinessAddress",
    "BusinessInventory",
    "BusinessLocation",
    "Client",
    "ClientAddress",
    "Coordinates",
    "CommissionPayout",
    "CountryDeliveryConfig",
    "DeliveryConfig",
    "DeliveryTimeSlot",
    "DeliveryTimeWindow",
    "DocumentType",
    "EntityType",
    "GoogleDistanceCache",
    "GoogleGeocodeCache",
    "Item",
    "ItemCategory",
    "ItemImage",
    "ItemSubCategory",
    "MobilePaymentTransaction",
    "MtnMomoPaymentRequest",
    "Order",
    "OrderCancellationReason",
    "OrderHold",
    "OrderItem",
    "OrderStatuHistory",
    "Partner",
    "PaymentCallback",
    "Rating",
    "RatingAggregate",
    "SupportedCountryState",
    "SupportedPaymentSystem",
    "User",
    "UserMessage",
    "UserType",
    "UserUpload",
    "VehicleType",
    "TransactionInfo",
]
