export const SITE_EVENT_TYPES_V1 = [
  'inventory.cta.buy_now_click',
  'inventory.cta.order_now_click',
  'inventory.cta.browse_more_click',
  'inventory.cta.faq_toggle',
  'inventory.cta.rating_summary_click',
  'inventory.cta.contact_before_buy_click',
  'inventory.search.submit',
  'inventory.search.suggestion_select',
  'inventory.sort.select',
  'inventory.filter.change',
  'inventory.filter.clear',
  'inventory.location.select',
  'inventory.card.view_details_click',
  'inventory.card.image_lightbox_open',
  'inventory.checkout_dialog.open',
  'inventory.checkout_dialog.continue_click',
  'inventory.checkout_dialog.auth_redirect',
  'checkout.delivery_unavailable_shown',
  'checkout.switched_to_pickup',
  'checkout.order_created_pickup',
  // Market (mobile)
  'market.auto_detected',
  'market.changed',
  'market.change_prompt_shown',
  'market.change_prompt_accepted',
  'market.change_prompt_dismissed',
  // Cancellation funnel (mobile)
  'cancellation.dialog_opened',
  'cancellation.preview_loaded',
  'cancellation.preview_failed',
  'cancellation.reason_selected',
  'cancellation.confirmed',
  'cancellation.abandoned',
  'cancellation.blocked_shown',
  // Product create funnel (mobile)
  'product_create.flow_opened',
  'product_create.photo_captured',
  'product_create.photo_upload_completed',
  'product_create.hint_shown',
  'product_create.hint_submitted',
  'product_create.hint_skipped',
  'product_create.ai_suggestions_returned',
  'product_create.ai_failed',
  'product_create.field_edited',
  'product_create.duplicate_warning_shown',
  'product_create.duplicate_add_stock_chosen',
  'product_create.preview_opened',
  'product_create.published',
  'product_create.saved_for_later',
  'product_create.draft_resumed',
  'product_create.add_another_tapped',
  'product_create.enrichment_nudge_shown',
  'product_create.enrichment_nudge_accepted',
  // FTUE / onboarding (mobile)
  'ftue.onboarding.started',
  'ftue.onboarding.screen_viewed',
  'ftue.onboarding.skipped',
  'ftue.onboarding.completed',
  'ftue.persona_intent.selected',
  'ftue.persona_intent.changed',
  'ftue.hero.slide_viewed',
  'ftue.hero.cta_clicked',
  'ftue.nudge.shown',
  'ftue.nudge.clicked',
  'ftue.nudge.dismissed',
  'ftue.checklist.viewed',
  'ftue.checklist.step_completed',
  'ftue.signup.started',
  'ftue.signup.completed',
  'ftue.browse.session_started',
  'ftue.browse.product_viewed',
] as const;

export type SiteEventTypeV1 = (typeof SITE_EVENT_TYPES_V1)[number];

export const SITE_EVENT_SUBJECT_INVENTORY_ITEM = 'inventory_item';
