"""
Pydantic models generated from Hasura metadata.

Models are generated by `generate_models.py` into individual files in this
package and re-exported here via the `__all__` list for convenient imports.

Usage:
    from models.User import User
"""

from typing import List, Type

from pydantic import BaseModel


def _discover_models() -> List[Type[BaseModel]]:
    """
    Discover all Pydantic models defined in this package.

    This is intentionally lightweight: it only inspects already-imported
    modules to avoid side effects on import. The generator script is
    responsible for keeping this file up to date when new models are added.
    """
    models: List[Type[BaseModel]] = []
    globals_copy = dict(globals())
    for value in globals_copy.values():
        if isinstance(value, type) and issubclass(value, BaseModel):
            if value is not BaseModel:
                models.append(value)
    return models


__all__ = [model.__name__ for model in _discover_models()]


