name: Deploy CDK Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'apps/cdk/**'
      - 'package.json'
      - 'nx.json'
      - 'tsconfig.base.json'
      - '.github/workflows/deploy-cdk.yml'

  workflow_dispatch:

env:
  AWS_REGION: ca-central-1
  CDK_ENVIRONMENT: development

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Bootstrap CDK (if needed)
        run: |
          cd apps/cdk
          cdk bootstrap --require-approval never || echo "CDK already bootstrapped"

      - name: Build CDK app
        run: |
          cd apps/cdk
          npm run build

      - name: Synthesize CDK template
        run: |
          cd apps/cdk
          cdk synth --context environment=${{ env.CDK_ENVIRONMENT }}

      - name: Deploy CDK infrastructure
        run: |
          cd apps/cdk
          cdk deploy --context environment=${{ env.CDK_ENVIRONMENT }} --require-approval never
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ env.AWS_REGION }}

      - name: Verify deployment
        run: |
          echo "CDK deployment completed successfully!"
          echo "Environment: ${{ env.CDK_ENVIRONMENT }}"
          echo "Region: ${{ env.AWS_REGION }}"
          echo "Deployed resources:"
          cd apps/cdk
          cdk list --context environment=${{ env.CDK_ENVIRONMENT }}
